config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello from post it!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in_user user
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out_user
    redirect_to root_url
  end

  private
  def log_in_user(user)
    session[:user_id] = user.id
  end

  def log_out_user
    reset_session
    @current_user = nil
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in_user @user
      flash[:success] = "Welcome to the Postit App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
    end

    def log_in_user(user)
      session[:user_id] = user.id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">2023</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark d-flex flex-wrap justify-content-center">
  <div class="container-fluid">
    <%= link_to "Postit!", root_path, id: "logo"  , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 float-end">
        <li class="nav-item"><%= link_to "Home",  root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Help", help_path, class: "nav-link" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Users", '#', class: "nav-link" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Profile", current_user, class:"dropdown-item" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class:"dropdown-item" %></li>
              <li class="dropdown-divider"></li>
              <li>
                <%= button_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path  , class: "nav-link"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="my-3 alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  Keith is a passionate and experienced Ruby on Rails software developer with over 5 years of industry experience.
  He is known for his expertise in building scalable and efficient web applications using Ruby on Rails framework.
</p>

<p>
  Keith's journey as a developer started during his university years,
  where he was captivated by the elegant syntax and the developer-friendly ecosystem of Ruby on Rails.
  He quickly gained proficiency in the framework and went on to hone his skills through various internships and projects.
</p>

<p>
  Throughout his career, Keith has worked with startups, mid-sized companies, and Fortune 500 enterprises,
  delivering high-quality solutions that meet the needs of both clients and end-users.
  He has a proven track record of designing and implementing complex web applications,
  utilizing his deep understanding of Ruby on Rails conventions, MVC architecture, and RESTful APIs.
</p>

<p>
  Keith is also skilled in front-end technologies such as HTML5, CSS3, and JavaScript,
  and has a keen eye for creating intuitive user interfaces that provide seamless user experiences.
  He is well-versed in version control systems like Git and
  has experience working with databases like MySQL, PostgreSQL, and MongoDB.
</p>

<p>
  As a continuous learner, Keith stays up-to-date with the latest advancements in the Ruby on Rails ecosystem
  and constantly seeks opportunities to enhance his skills.
  He is also a strong advocate of clean code practices, test-driven development (TDD), and agile methodologies.
</p>

<p>
  Outside of coding, Keith enjoys hiking, playing the guitar,
  and participating in hackathons and coding challenges to further challenge and develop his skills.
  With his technical expertise, dedication, and passion for creating robust and user-friendly web applications,
  Keith is a valuable asset to any software development team.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> <h1>Contact</h1>
<p>
  Contact the Keith about the sample app at the
  <a href="#">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  To follow guides on the Ruby on Rails
  <a href="https://guides.rubyonrails.org/">Rails Guides page</a>.
  To get help from the community, see the
  <a href="https://discuss.rubyonrails.org/"><em>Ruby on Rails Discussions</em></a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">PostIt App</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Post away your thoughts to infinity
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= link_to "Sign up", signup_path  , class: "btn btn-primary btn-lg px-4"%>
      <%= link_to "Login", login_path  , class: "btn btn-outline-secondary btn-lg px-4 ml-5"%>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1 class="mt-5">Update your profile</h1>

<div class="row">
  <div class="col-md-6 mb-4">
    <%= form_with(model: @user, local: true) do |editForm| %>
      <%= render 'shared/error_messages' %>

      <%= editForm.label :name, class: "form-label" %>
      <%= editForm.text_field :name, class: 'form-control mb-3' %>

      <%= editForm.label :email, class: "form-label" %>
      <%= editForm.email_field :email, class: 'form-control mb-3' %>

      <%= editForm.label :password, class: "form-label" %>
      <%= editForm.password_field :password, class: 'form-control mb-3' %>

      <%= editForm.label :password_confirmation, "Confirmation", class: "form-label" %>
      <%= editForm.password_field :password_confirmation, class: 'form-control mb-3' %>

      <%= editForm.submit "Save changes", class: "btn btn-primary btn-lg my-3" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="form-signup">
  <h1 class="mt-5">Sign up</h1>
  <div class="row">
    <div class="col-md-6 mb-4">
      <%= form_with(model: @user, local: true) do |form| %>
        <%= render 'shared/error_messages' %>

        <%= form.label(:name, class: "form-label") %>
        <%= form.text_field(:name, class: "form-control mb-3") %>

        <%= form.label(:email, class: "form-label") %>
        <%= form.email_field(:email, class: "form-control mb-3") %>

        <%= form.label(:password, class: "form-label") %>
        <%= form.password_field(:password, class: "form-control mb-3") %>

        <%= form.label(:password_confirmation, class: "form-label", ) %>
        <%= form.password_field(:password_confirmation, class: "form-control mb-3") %>

        <%= form.submit "Create my account", class: "btn btn-primary btn-lg my-3" %> <% end %>

        <hr class="my-4">
      <small class="text-muted">By clicking <em>Create my account</em>, you agree to the terms of use.</small>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <h1 class="mt-4">
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
</div>